#!/usr/bin/env node

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const lessonsDir = path.join(__dirname, '../src/lib/lessons');

// Find all lesson files matching pattern: X-Y-name.ts
const files = fs.readdirSync(lessonsDir)
  .filter(f => /^\d-\d-.+\.ts$/.test(f) && !f.includes('index'))
  .sort();

if (files.length === 0) {
  console.warn('⚠️  No lesson files found in', lessonsDir);
  process.exit(1);
}

// Generate imports
const imports = files.map((f, i) =>
  `import { lesson as lesson${i} } from './${f.replace('.ts', '')}';`
).join('\n');

// Generate the index.ts file
const output = `// Auto-generated by scripts/generate-lessons.mjs
// DO NOT EDIT MANUALLY - add new lesson files and run: npm run generate:lessons

import { Lesson, Part } from './types';

${imports}

export const lessons: Lesson[] = [
${files.map((_, i) => `  lesson${i},`).join('\n')}
].sort((a, b) =>
  a.partNumber === b.partNumber
    ? a.lessonNumber - b.lessonNumber
    : a.partNumber - b.partNumber
);

export const parts: Part[] = lessons.reduce((acc, lesson) => {
  let part = acc.find(p => p.number === lesson.partNumber);
  if (!part) {
    part = { number: lesson.partNumber, title: lesson.partTitle, lessons: [] };
    acc.push(part);
  }
  part.lessons.push(lesson);
  return acc;
}, [] as Part[]);

export function getLessonBySlug(slug: string): Lesson | undefined {
  return lessons.find(l => l.slug === slug);
}

export function getNextLesson(currentSlug: string): Lesson | undefined {
  const index = lessons.findIndex(l => l.slug === currentSlug);
  return index >= 0 && index < lessons.length - 1 ? lessons[index + 1] : undefined;
}

export function getPrevLesson(currentSlug: string): Lesson | undefined {
  const index = lessons.findIndex(l => l.slug === currentSlug);
  return index > 0 ? lessons[index - 1] : undefined;
}
`;

// Write the generated file
const outputPath = path.join(lessonsDir, 'index.ts');
fs.writeFileSync(outputPath, output, 'utf-8');

console.log(`✅ Generated index.ts with ${files.length} lessons:`);
files.forEach((f, i) => {
  console.log(`   ${i + 1}. ${f.replace('.ts', '')}`);
});
