// Auto-generated by scripts/generate-lessons.mjs
// DO NOT EDIT MANUALLY — regenerate with: npm run generate:lessons

import { Lesson, Part } from './types';

import { lesson as lesson0 } from './1-1-hello-kindscript.generated';
import { lesson as lesson1 } from './1-2-catching-violations.generated';
import { lesson as lesson2 } from './1-3-fix-the-violation.generated';
import { lesson as lesson3 } from './2-1-pure-layers.generated';
import { lesson as lesson4 } from './2-2-fix-purity.generated';
import { lesson as lesson5 } from './3-1-detecting-cycles.generated';
import { lesson as lesson6 } from './3-2-break-the-cycle.generated';
import { lesson as lesson7 } from './4-1-atom-source.generated';
import { lesson as lesson8 } from './4-2-atom-story.generated';
import { lesson as lesson9 } from './4-3-atom-version.generated';
import { lesson as lesson10 } from './4-4-full-atom.generated';
import { lesson as lesson11 } from './5-1-molecule-source.generated';
import { lesson as lesson12 } from './5-2-molecule-story.generated';
import { lesson as lesson13 } from './5-3-molecule-version.generated';
import { lesson as lesson14 } from './5-4-full-molecule.generated';
import { lesson as lesson15 } from './6-1-wrapped-kinds.generated';
import { lesson as lesson16 } from './6-2-tagged-purity.generated';
import { lesson as lesson17 } from './6-3-tagged-boundaries.generated';
import { lesson as lesson18 } from './7-1-bounded-contexts.generated';
import { lesson as lesson19 } from './7-2-exhaustive-enforcement.generated';
import { lesson as lesson20 } from './8-1-full-stack-architecture.generated';

export const lessons: Lesson[] = [
  lesson0,
  lesson1,
  lesson2,
  lesson3,
  lesson4,
  lesson5,
  lesson6,
  lesson7,
  lesson8,
  lesson9,
  lesson10,
  lesson11,
  lesson12,
  lesson13,
  lesson14,
  lesson15,
  lesson16,
  lesson17,
  lesson18,
  lesson19,
  lesson20,
].sort((a, b) =>
  a.partNumber === b.partNumber
    ? a.lessonNumber - b.lessonNumber
    : a.partNumber - b.partNumber
);

export const parts: Part[] = lessons.reduce((acc, lesson) => {
  let part = acc.find(p => p.number === lesson.partNumber);
  if (!part) {
    part = { number: lesson.partNumber, title: lesson.partTitle, lessons: [] };
    acc.push(part);
  }
  part.lessons.push(lesson);
  return acc;
}, [] as Part[]);

export function getLessonBySlug(slug: string): Lesson | undefined {
  return lessons.find(l => l.slug === slug);
}

export function getNextLesson(currentSlug: string): Lesson | undefined {
  const index = lessons.findIndex(l => l.slug === currentSlug);
  return index >= 0 && index < lessons.length - 1 ? lessons[index + 1] : undefined;
}

export function getPrevLesson(currentSlug: string): Lesson | undefined {
  const index = lessons.findIndex(l => l.slug === currentSlug);
  return index > 0 ? lessons[index - 1] : undefined;
}
