// Auto-generated storybook files for tutorial lessons
// Source: tutorial-assets/storybook/
// Generated by: scripts/load-storybook-files.mjs

import { LessonFile } from './types';
import storybookFilesData from '../../../tutorial-assets/storybook-files.json';

/**
 * All storybook files loaded from tutorial-assets/storybook/
 * Total: 345 files from the induction-studio storybook app
 */
export const storybookFiles: LessonFile[] = storybookFilesData as LessonFile[];

/**
 * Get storybook files with a custom prefix (default: 'storybook/')
 * This allows mounting the storybook files at a specific path in the lesson
 */
export function getStorybookFiles(prefix: string = 'storybook/'): LessonFile[] {
  return storybookFiles.map(file => ({
    path: `${prefix}${file.path}`,
    contents: file.contents
  }));
}

/**
 * Filter storybook files by directory pattern
 */
export function filterStorybookFiles(pattern: string | RegExp): LessonFile[] {
  const regex = typeof pattern === 'string' ? new RegExp(pattern) : pattern;
  return storybookFiles.filter(file => regex.test(file.path));
}

/**
 * Get only atom components (buttons, inputs, etc.)
 */
export function getAtomFiles(): LessonFile[] {
  return filterStorybookFiles(/^src\/components\/atoms\//);
}

/**
 * Get only molecule components (cards, sidebars, etc.)
 */
export function getMoleculeFiles(): LessonFile[] {
  return filterStorybookFiles(/^src\/components\/molecules\//);
}

/**
 * Get common utilities and shared code
 */
export function getCommonFiles(): LessonFile[] {
  return filterStorybookFiles(/^src\/(common|core|utils|mocks)\//);
}
